### ISSUE TITLE
怎么保证jquery load before admimLte下的app.js

### ISSUE THREAD

**Issue by artdong** [Gezii/vue2-AdminLTE#2]
怎么保证jquery load before admimLte下的app.js
我自己一步一步搭建，报app.js require jquery，帮忙解决一下，谢谢

![default](https://cloud.githubusercontent.com/assets/16631463/24337305/2698ef46-12ce-11e7-85f1-1ef31e98e2af.png)

**Comment by Gezii** [comment]
在build/webpack.base.conf.js里有配置jquery的，你看看你的node_modules里有没有正确安装jquery.

  ```
plugins: [
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery"
    })
   ]
```

**Comment by artdong** [comment]
已解决，谢谢
