### ISSUE TITLE
iCheck样式问题

### ISSUE THREAD

**Issue by artdong** [Gezii/vue2-AdminLTE#3]
iCheck样式没有渲染出来

**Comment by artdong** [comment]
就是登录界面那个记住我复选框样式没应用上
安装了icheck插件，也引入了@import '~icheck/skins/square/blue.css';
还是没效果

**Comment by Gezii** [comment]
建议使用 [element](https://github.com/ElemeFE/element)

**Comment by artdong** [comment]
ok,3q
